title: Eric Han
url: "https://eric-han.com"
baseurl: ""

logo: eh.png
social:
  name: Eric Han
  links:
    - https://sg.linkedin.com/in/eric-han-lw
    - https://github.com/eric-vader
    - https://bitbucket.org/eric_vader

markdown: kramdown
#ins_logo: "./NUS_logo.jpg"
mathjax: true

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CS6216"
   link: "CS6216"
 - name: "Introduction"
   link: "Introduction"
 - name: "Kernel"
   link: "Kernel"
 - name: "Feature Selection"
   link: "Feature Selection"
# - name: "Resume"
#   link: "misc/resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "About"
   link: "/"

twitter_username: eric_vader
favicon_location: /favicon.ico

plugins:
  - jekyll-seo-tag
  
  

