title: Eric Han
url: "https://eric-han.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./NUS_logo.jpg"
mathjax: true

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Introduction"
   link: "Introduction"
 - name: "Kernel"
   link: "Kernel"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "About"
   link: "/"

