title: Eric Han
description: A PhD Students' resume, Research Notes and Teaching Notes.
author: Eric Han
url: "https://eric-han.com"
baseurl: ""

logo: eh.png
social:
  name: Eric Han
  links:
    - https://sg.linkedin.com/in/eric-han-lw
    - https://github.com/eric-vader
    - https://bitbucket.org/eric_vader

defaults:
  -
    scope:
      path: "*"
    values:
      layout: "default"

markdown: kramdown
#ins_logo: "./NUS_logo.jpg"
mathjax: true

favicon: yes

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Contact"
   link: "contact"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Gallery"
   link: "gallery"

collections:
  steps:
    title: Steps
    output: false
  research:
    title: Research
    output: false

plugins:
  - jekyll-seo-tag

img_path: img

# whitelist: [jekyll-analytics]
